# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.coa_templates_api import CoaTemplatesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestCoaTemplatesApi(unittest.TestCase):
    """CoaTemplatesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.coa_templates_api.CoaTemplatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_coa_templates(self):
        """Test case for get_coa_templates

        Returns all Coa Templates  # noqa: E501
        """
        pass

    def test_get_coa_templates_key(self):
        """Test case for get_coa_templates_key

        Returns a Coa Template  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
