# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.other_payment import OtherPayment  # noqa: E501
from openapi_client.rest import ApiException

class TestOtherPayment(unittest.TestCase):
    """OtherPayment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test OtherPayment
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.other_payment.OtherPayment()  # noqa: E501
        if include_optional :
            return OtherPayment(
                legacy_id = 56, 
                id = '0', 
                displayed_as = '0', 
                path = '0', 
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                transaction = openapi_client.models.base.Base(
                    legacy_id = 56, 
                    id = '0', 
                    displayed_as = '0', 
                    __path = '0', ), 
                transaction_type = openapi_client.models.base.Base(
                    legacy_id = 56, 
                    id = '0', 
                    displayed_as = '0', 
                    __path = '0', ), 
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                payment_method = openapi_client.models.base.Base(
                    legacy_id = 56, 
                    id = '0', 
                    displayed_as = '0', 
                    __path = '0', ), 
                contact = openapi_client.models.base.Base(
                    legacy_id = 56, 
                    id = '0', 
                    displayed_as = '0', 
                    __path = '0', ), 
                bank_account = openapi_client.models.base.Base(
                    legacy_id = 56, 
                    id = '0', 
                    displayed_as = '0', 
                    __path = '0', ), 
                tax_address_region = openapi_client.models.base.Base(
                    legacy_id = 56, 
                    id = '0', 
                    displayed_as = '0', 
                    __path = '0', ), 
                date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                net_amount = 1.337, 
                tax_amount = 1.337, 
                total_amount = 1.337, 
                reference = '0', 
                payment_lines = [
                    openapi_client.models.other_payment_line_item.OtherPaymentLineItem(
                        legacy_id = 56, 
                        id = '0', 
                        displayed_as = '0', 
                        ledger_account = openapi_client.models.base.Base(
                            legacy_id = 56, 
                            id = '0', 
                            displayed_as = '0', 
                            __path = '0', ), 
                        details = '0', 
                        tax_rate = openapi_client.models.base.Base(
                            legacy_id = 56, 
                            id = '0', 
                            displayed_as = '0', 
                            __path = '0', ), 
                        net_amount = 1.337, 
                        tax_amount = 1.337, 
                        total_amount = 1.337, 
                        tax_breakdown = [
                            openapi_client.models.tax_breakdown.TaxBreakdown(
                                percentage = 1.337, 
                                amount = 1.337, )
                            ], 
                        is_purchase_for_resale = True, 
                        trade_of_asset = True, 
                        gst_amount = 1.337, 
                        pst_amount = 1.337, )
                    ], 
                editable = True, 
                deletable = True, 
                withholding_tax_rate = 1.337, 
                withholding_tax_amount = 1.337
            )
        else :
            return OtherPayment(
        )

    def testOtherPayment(self):
        """Test OtherPayment"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
