# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.post_business_exchange_rates import PostBusinessExchangeRates  # noqa: E501
from openapi_client.rest import ApiException

class TestPostBusinessExchangeRates(unittest.TestCase):
    """PostBusinessExchangeRates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PostBusinessExchangeRates
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.post_business_exchange_rates.PostBusinessExchangeRates()  # noqa: E501
        if include_optional :
            return PostBusinessExchangeRates(
                business_exchange_rate = openapi_client.models.post_business_exchange_rates_business_exchange_rate.postBusinessExchangeRates_business_exchange_rate(
                    currency_id = '0', 
                    rate = 1.337, 
                    inverse_rate = 1.337, 
                    base_currency_id = '0', )
            )
        else :
            return PostBusinessExchangeRates(
        )

    def testPostBusinessExchangeRates(self):
        """Test PostBusinessExchangeRates"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
