# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.post_addresses import PostAddresses  # noqa: E501
from openapi_client.rest import ApiException

class TestPostAddresses(unittest.TestCase):
    """PostAddresses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PostAddresses
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.post_addresses.PostAddresses()  # noqa: E501
        if include_optional :
            return PostAddresses(
                address = openapi_client.models.post_addresses_address.postAddresses_address(
                    address_type_id = '0', 
                    name = '0', 
                    is_main_address = True, 
                    bank_account_id = '0', 
                    contact_id = '0', 
                    address_line_1 = '0', 
                    address_line_2 = '0', 
                    city = '0', 
                    region = '0', 
                    postal_code = '0', 
                    country_id = '0', 
                    country_group_id = '0', )
            )
        else :
            return PostAddresses(
        )

    def testPostAddresses(self):
        """Test PostAddresses"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
