# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.bank_account_types_api import BankAccountTypesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestBankAccountTypesApi(unittest.TestCase):
    """BankAccountTypesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.bank_account_types_api.BankAccountTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_bank_account_types(self):
        """Test case for get_bank_account_types

        Returns all Bank Account Types  # noqa: E501
        """
        pass

    def test_get_bank_account_types_key(self):
        """Test case for get_bank_account_types_key

        Returns a Bank Account Type  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
