# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.contact_allocation import ContactAllocation  # noqa: E501
from openapi_client.rest import ApiException

class TestContactAllocation(unittest.TestCase):
    """ContactAllocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ContactAllocation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.contact_allocation.ContactAllocation()  # noqa: E501
        if include_optional :
            return ContactAllocation(
                legacy_id = 56, 
                id = '0', 
                displayed_as = '0', 
                path = '0', 
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                links = [
                    openapi_client.models.link.Link(
                        href = '0', 
                        rel = '0', 
                        type = '0', )
                    ], 
                transaction = openapi_client.models.base.Base(
                    legacy_id = 56, 
                    id = '0', 
                    displayed_as = '0', 
                    __path = '0', ), 
                transaction_type = openapi_client.models.base.Base(
                    legacy_id = 56, 
                    id = '0', 
                    displayed_as = '0', 
                    __path = '0', ), 
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                contact = openapi_client.models.base.Base(
                    legacy_id = 56, 
                    id = '0', 
                    displayed_as = '0', 
                    __path = '0', ), 
                allocated_artefacts = [
                    openapi_client.models.allocated_artefact.AllocatedArtefact(
                        legacy_id = 56, 
                        id = '0', 
                        artefact = openapi_client.models.generic.Generic(
                            legacy_id = 56, 
                            id = '0', 
                            displayed_as = '0', 
                            __path = '0', 
                            links = [
                                openapi_client.models.link.Link(
                                    href = '0', 
                                    rel = '0', 
                                    type = '0', )
                                ], ), 
                        amount = 1.337, )
                    ]
            )
        else :
            return ContactAllocation(
        )

    def testContactAllocation(self):
        """Test ContactAllocation"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
