# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.migrations_api import MigrationsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestMigrationsApi(unittest.TestCase):
    """MigrationsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.migrations_api.MigrationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_migrations(self):
        """Test case for get_migrations

        Returns all Migrations  # noqa: E501
        """
        pass

    def test_put_migrations(self):
        """Test case for put_migrations

        Updates a Migrations  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
