# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class AddressRegion(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'legacy_id': 'int',
        'id': 'str',
        'name': 'str',
        'path': 'str',
        'code': 'str',
        'displayed_as': 'str'
    }

    attribute_map = {
        'legacy_id': 'legacy_id',
        'id': 'id',
        'name': 'name',
        'path': '$path',
        'code': 'code',
        'displayed_as': 'displayed_as'
    }

    def __init__(self, legacy_id=None, id=None, name=None, path=None, code=None, displayed_as=None, local_vars_configuration=None):  # noqa: E501
        """AddressRegion - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._legacy_id = None
        self._id = None
        self._name = None
        self._path = None
        self._code = None
        self._displayed_as = None
        self.discriminator = None

        if legacy_id is not None:
            self.legacy_id = legacy_id
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if path is not None:
            self.path = path
        if code is not None:
            self.code = code
        if displayed_as is not None:
            self.displayed_as = displayed_as

    @property
    def legacy_id(self):
        """Gets the legacy_id of this AddressRegion.  # noqa: E501

        The legacy ID for the item  # noqa: E501

        :return: The legacy_id of this AddressRegion.  # noqa: E501
        :rtype: int
        """
        return self._legacy_id

    @legacy_id.setter
    def legacy_id(self, legacy_id):
        """Sets the legacy_id of this AddressRegion.

        The legacy ID for the item  # noqa: E501

        :param legacy_id: The legacy_id of this AddressRegion.  # noqa: E501
        :type: int
        """

        self._legacy_id = legacy_id

    @property
    def id(self):
        """Gets the id of this AddressRegion.  # noqa: E501

        The unique identifier for the item  # noqa: E501

        :return: The id of this AddressRegion.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AddressRegion.

        The unique identifier for the item  # noqa: E501

        :param id: The id of this AddressRegion.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                id is not None and len(id) > 10):
            raise ValueError("Invalid value for `id`, length must be less than or equal to `10`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this AddressRegion.  # noqa: E501

        The name of the address region  # noqa: E501

        :return: The name of this AddressRegion.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AddressRegion.

        The name of the address region  # noqa: E501

        :param name: The name of this AddressRegion.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def path(self):
        """Gets the path of this AddressRegion.  # noqa: E501

        The API path for the resource  # noqa: E501

        :return: The path of this AddressRegion.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this AddressRegion.

        The API path for the resource  # noqa: E501

        :param path: The path of this AddressRegion.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def code(self):
        """Gets the code of this AddressRegion.  # noqa: E501

        The code of the address region  # noqa: E501

        :return: The code of this AddressRegion.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this AddressRegion.

        The code of the address region  # noqa: E501

        :param code: The code of this AddressRegion.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                code is not None and len(code) > 8):
            raise ValueError("Invalid value for `code`, length must be less than or equal to `8`")  # noqa: E501

        self._code = code

    @property
    def displayed_as(self):
        """Gets the displayed_as of this AddressRegion.  # noqa: E501

        Display text for the item  # noqa: E501

        :return: The displayed_as of this AddressRegion.  # noqa: E501
        :rtype: str
        """
        return self._displayed_as

    @displayed_as.setter
    def displayed_as(self, displayed_as):
        """Sets the displayed_as of this AddressRegion.

        Display text for the item  # noqa: E501

        :param displayed_as: The displayed_as of this AddressRegion.  # noqa: E501
        :type: str
        """

        self._displayed_as = displayed_as

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddressRegion):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AddressRegion):
            return True

        return self.to_dict() != other.to_dict()
